MusicRising/Controllers/BandsController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Net.Mime;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using MusicRising.Data.Services;
using MusicRising.Helpers;
using MusicRising.Models;

namespace MusicRising.Controllers
{
    public class BandsController : Controller
    {
        private readonly IBandsService _bandsService;
        private readonly IVenuesService _venuesService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly UserManager<IdentityUser> _userManager;
        private readonly DebugHelper _debugHelper = new DebugHelper();

        public BandsController(IBandsService bandsService, UserManager<IdentityUser> userManager,
            IWebHostEnvironment webHostEnvironment, IVenuesService venuesService)
        {
            _bandsService = bandsService;
            _venuesService = venuesService;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
        }
        
        // GET: Bands
        // when a selection button is clicked filter for that selection and reload view
        //bool liked will be used to show liked bands or v enues only but that it not jet inplemented
        public async Task<IActionResult> Index(string location, string genre, bool liked = false)
        {
            var bands = await _bandsService.GetAll().ToListAsync();

            if (!string.IsNullOrEmpty(location))
            {
                bands = bands.Where(b => b.Location.ToString() == location).ToList();
            }

            if (!string.IsNullOrEmpty(genre))
            {
                bands = bands.Where(b => b.Genre.ToString() == genre).ToList();
            }

            // 
            /*if (liked)
            {
                // if user has band in his liked list.....//
            }*/

            ViewData["Location"] = new SelectList(Enum.GetValues(typeof(LocationEnum)).Cast<LocationEnum>());
            ViewData["Genre"] = new SelectList(Enum.GetValues(typeof(GenreEnum)).Cast<GenreEnum>());
            ViewData["Liked"] = true;

            return View(bands);
        }

        // GET: Bands/Landing
        // this is used to show all bands a user has or go and create one
        public async Task<IActionResult> Landing()
        {
            var userId = _userManager.GetUserId(User);
            var userBands = await _bandsService.GetAll()
                .Where(b => b.IdentityUserId == userId)
                .ToListAsync();
            
                return View(userBands);

        }

        // GET: Bands/Details/5
        // if the user is the bandmember that registered this band he can edit or delete
        
        public async Task<IActionResult> Details(string id)
        {
            // tu use this the band should exist
            if (id == null)
            {
                return NotFound();
            }

            var band = await _bandsService.GetAll()
                .Include(b => b.User)
                .FirstOrDefaultAsync(b => b.BandId == id);
            if (band == null)
            {
                return NotFound();
            }
            

            // create viewmodel to get beter / other data then in model
            var bandVM = new BandVM
            {
                BandId = band.BandId,
                IdentityUserId = band.IdentityUserId,
                User = band.User,
                BandName = band.BandName,
                Image = null,
                ImageFileName = band.BandPicture,
                Location = band.Location,
                Genre = band.Genre,
                Shows = band.Shows,
                PromoItems = band.PromoItems,
                Ratings = band.Ratings,
                Details = band.Details,
                Address = band.Address,
                Latitude = band.Latitude,
                Longitude = band.Longitude,
                IsOwner = band.IdentityUserId == _userManager.GetUserId(User),
                CanBeBooked = _venuesService.IsVenueHolder(_userManager.GetUserId(User))
            };

            return View(bandVM);
        }

        // GET: Bands/Create
        public IActionResult Create()
        {
            ViewData["IdentityUserId"] = new SelectList(_userManager.Users, "Id", "Id");
            return View();
        }

        // POST: Bands/Create
        // we use a bandvm to present and get data
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(BandVM band)
        {
            if (_userManager.GetUserId(User) == null) return RedirectToAction(nameof(Index));

            
            // if you create a band you should upload image
            if (band.Image != null)
            {
                string filePath = ImageHelper.SaveImageToServer(_webHostEnvironment, band.Image);
                _debugHelper.DebugWriteLine("filepath = " + filePath);
                _debugHelper.DebugWriteLine("image name = " + band.Image.FileName);
                var bandCoordinates = await GeocodingHelper.GetCoordinatesAsync(band.Address);

                var bandObj = new Band
                {
                    BandId = Guid.NewGuid().ToString(),
                    IdentityUserId = band.IdentityUserId,
                    User = band.User,
                    BandName = band.BandName,
                    BandPicture = filePath,
                    Location = band.Location,
                    Genre = band.Genre,
                    Details = band.Details,
                    Latitude = bandCoordinates.Latitude,
                    Longitude = bandCoordinates.Longitude,
                    Address = band.Address
                };

                await _bandsService.Add(bandObj);
                return RedirectToAction(nameof(Index));
            }

            ViewData["IdentityUserId"] = new SelectList(_userManager.Users, "Id", "Id", band.IdentityUserId);
            return View(band);
        }

        // GET: Bands/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            
            if (id == null)
            {
                return NotFound();
            }

            var band = await _bandsService.GetAll().FirstOrDefaultAsync(b => b.BandId == id);
            if (band == null)
            {
                return NotFound();
            }
            
            if (!AuthHelper.Authorize(_userManager.GetUserId(User), band.IdentityUserId))
            {
                return RedirectToAction(nameof(Index));
            }

            var bandVM = new EntityEditVM
            {
                Id = band.BandId,
                IdentityUserId = band.IdentityUserId,
                Name = band.BandName,
                PictureUrl = band.BandPicture,
                Location = band.Location,
                Address = band.Address,
                Genre = band.Genre,
                Details = band.Details,
                IsOwner = band.IdentityUserId == _userManager.GetUserId(User)
            };

            ViewBag.Title = "Band";
            return View("_EntityEdit", bandVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, EntityEditVM bandVM)
        {
            if (!AuthHelper.Authorize(_userManager.GetUserId(User), bandVM.IdentityUserId))
            {
                return RedirectToAction(nameof(Index));
            }
            _debugHelper.DebugWriteLine($"Received edit request for band ID: {id}");
            // we do this to make shure someone did not get on this page by filling random url
            if (id != bandVM.Id)
            {
                return NotFound();
            }

            // debugging message to know if there is something wrong when uploading and image is not shown
            _debugHelper.DebugWriteLine("the picture url = " + bandVM.PictureUrl);

            if (bandVM != null)
            {
                try
                {
                    var band = await _bandsService.GetAll().FirstOrDefaultAsync(b => b.BandId == id);
                    if (band == null)
                    {
                        _debugHelper.DebugWriteLine("band was not found");
                        return NotFound();
                    }

                    if (bandVM.Picture != null)
                    {
                        _debugHelper.DebugWriteLine("foto update is there");
                        string filePath = ImageHelper.UpdateImageOnServer(_webHostEnvironment, bandVM.Picture, bandVM.PictureUrl);
                        bandVM.PictureUrl = filePath;
                    }

                    var bandCoordinates = await GeocodingHelper.GetCoordinatesAsync(bandVM.Address);

                    band.BandName = bandVM.Name;
                    band.Location = bandVM.Location;
                    band.Genre = bandVM.Genre;
                    band.BandPicture = bandVM.PictureUrl;
                    band.Latitude = bandCoordinates.Latitude;
                    band.Longitude = bandCoordinates.Longitude;
                    band.Details = bandVM.Details;
                    band.BankAccount = "NotImplementedJet";
                    band.Address = bandVM.Address;

                    _debugHelper.DebugWriteLine("before update band");

                    await _bandsService.Update(band);
                    _debugHelper.DebugWriteLine("after update band");
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!BandExists(bandVM.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }

MusicRising/Views/Shared/_Card.cshtml
@model dynamic

<div class="card mb-4" style="display: flex; flex-direction: row; width: 100%; height: 180px;">
    <div style="flex: 1;">
        <img class="card-img-left" src="~/Images/@Model.ImageUrl" alt="Card image cap" style="height: 100%; width: 100%; object-fit: cover; border-radius: 0;">
    </div>
    <div class="card-body" style="flex: 2; display: flex; flex-direction: column; justify-content: space-between;">
        <div>
            <h5 class="card-title">@Model.Title</h5>
            <p class="card-text">@Model.Description</p>
            <p class="card-text">@Model.Location</p>
            <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary">View Details</a>
        </div>
    </div>
</div>

MusicRising/Views/Shared/_DeleteConfirmation.cshtml
@model string

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h3>Confirm Deletion</h3>
        </div>
        <div class="card-body">
            <p>Are you sure you want to delete this item?</p>
            <form asp-action="DeleteConfirmed" method="post">
                <input type="hidden" name="id" value="@Model" />
                <button type="submit" class="btn btn-danger">Delete</button>
                <a asp-action="Edit" asp-route-id="@Model" class="btn btn-secondary">Cancel</a>
            </form>
        </div>
    </div>
</div>

MusicRising/Views/Shared/_EntityEdit.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using MusicRising.Helpers
@model MusicRising.Models.EntityEditVM

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h3>Edit @ViewBag.Title</h3>
        </div>
        <div class="card-body">
            <form asp-action="Edit" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <input type="hidden" asp-for="IdentityUserId" class="form-control" readonly />
                </div>
                <div class="form-group">
                    <input type="hidden" asp-for="Id" class="form-control" readonly />
                </div>
                <div class="form-group">
                    <input type="hidden" asp-for="PictureUrl" class="form-control" readonly />
                </div>
                <div class="form-group">
                    <label asp-for="Name" class="control-label">Name</label>
                    <input asp-for="Name" class="form-control" />
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">Picture</label>
                    <input asp-for="Picture" class="form-control" type="file" accept="image/*" />
                    <span asp-validation-for="Picture" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Location" class="control-label">Location</label>
                    <select asp-for="Location" class="form-control" asp-items="Html.GetEnumSelectList<LocationEnum>()"></select>
                    <span asp-validation-for="Location" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Genre" class="control-label">Genre</label>
                    <select asp-for="Genre" class="form-control" asp-items="Html.GetEnumSelectList<GenreEnum>()"></select>
                    <span asp-validation-for="Genre" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Edit" class="btn btn-primary" />
                    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
            @if (Model.IsOwner)
            {
            <form asp-action="Delete" method="post" onsubmit="return confirm('Are you sure you want to delete this item?');">
                <input type="hidden" asp-for="Id" />
                <button type="submit" class="btn btn-danger mt-3">Delete</button>
            </form>
            }
        </div>
    </div>
</div>

MusicRising/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using MusicRising.Helpers
@inject Microsoft.AspNetCore.Http.IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>@ViewData["Title"] - Music Rising</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css"/>
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true"/>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAMxdDwwsER-rLs4BHplNzZcXP11uooF-M"></script> <!--here we have to put the apikey if we get it-->
</head>
<body>
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark border-bottom box-shadow mb-3">
        <div class="container-fluid">
            <a class="navbar-brand d-flex align-items-center" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/Images/music-rising-logo.png" alt="Music Rising Logo" class="logo">
                <span>Music Rising</span>
            </a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>

                    @if (User.Identity.IsAuthenticated)
                    {
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Bands" asp-action="Landing">My Bands</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Venues" asp-action="Landing">My Venues</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" asp-area="" asp-controller="Shows" asp-action="Landing">My Shows</a>
                    </li>
                    }
                </ul>
                <partial name="_LoginPartial"/>
            </div>
        </div>
    </nav>
</header>

@{
// here we get the current page and if it is a page not having to do with finding bands/venues/etc we remove the bar from layout
var path = HttpContextAccessor.HttpContext.Request.Path.ToString().ToLower();
var showSelectionBar = !(path.Contains("/about") ||
path.Contains("/identity") ||
path.Contains("/home") ||
path.Contains("/bands/landing")||
path.Contains("/bands/details")||
path.Contains("/venues/landing")||
path.Contains("/venues/details")||
path.Contains("/shows/landing")||
path.Contains("/shows/details"));
}

@if (showSelectionBar)
{
<nav class="selection-bar">
    <div class="dropdown">
        <button class="selection dropdown-toggle" type="button" id="locationDropdown" data-bs-toggle="dropdown" aria-expanded="false">Location</button>
        <ul class="dropdown-menu" aria-labelledby="locationDropdown">
            @foreach (var location in Enum.GetValues(typeof(LocationEnum)).Cast<LocationEnum>())
            {
            <li><a class="dropdown-item" href="?location=@location">@location</a></li>
            }
        </ul>
    </div>
    <div class="divider"></div>
    <div class="dropdown">
        <button class="selection dropdown-toggle" type="button" id="genreDropdown" data-bs-toggle="dropdown" aria-expanded="false">Genre</button>
        <ul class="dropdown-menu" aria-labelledby="genreDropdown">
            @foreach (var genre in Enum.GetValues(typeof(GenreEnum)).Cast<GenreEnum>())
            {
            <li><a class="dropdown-item" href="?genre=@genre">@genre</a></li>
            }
        </ul>
    </div>
    <div class="divider"></div>
    <div class="dropdown">
        <button class="selection dropdown-toggle" type="button" id="likedDropdown" data-bs-toggle="dropdown" aria-expanded="false">Liked</button>
        <ul class="dropdown-menu" aria-labelledby="likedDropdown">
            <li><a class="dropdown-item" href="?liked=true">Liked</a></li>
            <li><a class="dropdown-item" href="?liked=false">Not Liked</a></li>
        </ul>
    </div>
</nav>
}

<nav class="bottom-nav">
    <a class="nav-btn" asp-area="" asp-controller="Shows" asp-action="Index">Shows</a>
    <div class="divider"></div>
    <a class="nav-btn" asp-area="" asp-controller="Bands" asp-action="Index">Bands</a>
    <div class="divider"></div>
    <a class="nav-btn" asp-area="" asp-controller="Venues" asp-action="Index">Venues</a>
</nav>
<div class="container">
    <main role="main" class="pb-3">
        @RenderBody()
    </main>
</div>
<footer class="footer text-muted">
    <div class="container">
        &copy; 2024 - Music Rising - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
</footer>
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
<script src="~/js/site.js" asp-append-version="true"></script>
@await RenderSectionAsync("Scripts", required: false)
</body>
</html>

MusicRising/Views/Shared/_ShowCard.cshtml
@model dynamic

<div class="card mb-4" style="display: flex; flex-direction: row; width: 100%; height: 180px;">
    <div style="flex: 1;">
        <img class="card-img-left" src="~/Images/@Model.ImageUrl" alt="Card image cap" style="height: 100%; width: 100%; object-fit: cover; border-radius: 0;">
    </div>
    <div class="card-body" style="flex: 2; display: flex; flex-direction: column; justify-content: space-between;">
        <div>
            <h5 class="card-title">@Model.Title</h5>
            <p class="card-text">@Model.Description</p>
            <p class="card-text"><small class="text-muted">Date: @Model.Date</small></p>
        </div>
        <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-primary align-self-start">View Details</a>
    </div>
</div>

MusicRising/Views/Shared/_ShowEntityEdit.cshtml
@using Microsoft.AspNetCore.Mvc.TagHelpers
@using MusicRising.Helpers
@model MusicRising.Models.EntityEditVM

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h3>Edit @ViewBag.Title</h3>
        </div>
        <div class="card-body">
            <form asp-action="Edit" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <input type="hidden" asp-for="IdentityUserId" class="form-control" readonly />
                </div>
                <div class="form-group">
                    <input type="hidden" asp-for="Id" class="form-control" readonly />
                </div>
                <div class="form-group">
                    <input type="hidden" asp-for="PictureUrl" class="form-control" readonly />
                </div>
                <div class="form-group">
                    <label asp-for="Picture" class="control-label">Picture</label>
                    <input asp-for="Picture" class="form-control" type="file" accept="image/*" />
                    <span asp-validation-for="Picture" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <input type="submit" value="Edit" class="btn btn-primary" />
                    <a asp-action="Index" class="btn btn-secondary">Cancel</a>
                </div>
            </form>
            @if (Model.IsOwner)
            {
            <form asp-action="Delete" method="post" onsubmit="return confirm('Are you sure you want to delete this item?');">
                <input type="hidden" asp-for="Id" />
                <button type="submit" class="btn btn-danger mt-3">Delete</button>
            </form>
            }
        </div>
    </div>
</div>

MusicRising/Views/Shared/_details.cshtml
@using Microsoft.AspNetCore.Identity
@model dynamic


<div class="container mt-4">
    <div class="card d-flex flex-row">
        <div class="col-md-4 p-0">
            @if (Model.ImageFileName != null)
            {
            <img src="~/Images/@Model.ImageFileName" alt="@Model.Title" class="img-fluid" style="height: 100%; width: 100%; object-fit: cover;">
            }
        </div>
        <div class="col-md-4">
            <div class="card-body">
                <h3 class="card-title">@Model.Title</h3>
                <dl class="row">
                    @foreach (var detail in Model.Details)
                    {
                        <dt class="col-sm-4">@detail.Key</dt>
                        <dd class="col-sm-8">@detail.Value</dd>
                    }
                </dl>
                
                @if (Model.IsOwner)
                {
                <a asp-action="Edit" asp-route-id="@Model.Id" class="btn btn-primary">Edit</a>
                }
                @if (Model.BookableLink)
                {
                <a asp-action="BookShow" asp-route-bandID="@Model.Id" class="btn btn-primary">Book us</a>
                }
                <a asp-action="Index" class="btn btn-secondary">Back to List</a>
            </div>
        </div>
        @if (Model.Latitude != null && Model.Longitude != null)
        {
        <div class="col-md-4 p-0">
            <div id="map" style="height: 100%; width: 100%;"></div>
        </div>
        }
    </div>
</div>

@section Scripts {
<script>
    function initMap() {
        var latitude = @Model.Latitude;
        var longitude = @Model.Longitude;
        var location = { lat: latitude, lng: longitude };
        var map = new google.maps.Map(document.getElementById('map'), {
            zoom: 15,
            center: location
        });
        var marker = new google.maps.Marker({
            position: location,
            map: map
        });
    }

    initMap();
</script>
}